
    project.radios = [
        {
              "id": 1,
               "name": "92.7",
               "tagline": "Suno Sunao, Life Banao!",
               "color": "0xffa11431",
               "desc": "The chills you get when you listen to music, is mostly caused by the brain releasing dopamine while anticipating the peak moment of a song.",
               "url": "https://strmreg.1.fm/bombaybeats_mobile_mp3",
               "icon": "https://mytuner.global.ssl.fastly.net/media/tvos_radios/m8afyszryaqt.png",
               "image": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/b5df4c18876369.562d0d4bd94cf.jpg",
               "lang": "Hindi",
               "category": "Bollywood",
               "disliked": false,
               "order": 1
           },
           {
               "id": 2,
               "name": "98.3",
               "tagline": "Gaano Ka Sweet Dish",
               "color": "0xff221420",
               "desc": "There are few activities in life that utilizes the entire brain, and music is one of them.",
               "url": "https://node-04.zeno.fm/4mbfcn4mf24tv?rj-ttl=5&rj-tok=AAABgQJk3A4AgoGF85rQjc2PEw",
               "icon": "https://static.mytuner.mobi/media/tvos_radios/2z69hnevkvam.jpeg",
               "image": "https://images.hungama.com/c/1/0cf/e78/36699135/36699135_300x300.jpg",
               "lang": "Hindi",
               "disliked": false,
               "category": "Punjabi",
               "order": 2
           },
           {
               "id": 3,
               "name": "102",
               "tagline": "Play On!",
               "color": "0xff04080b",
               "desc": "Playing music regularly will physically alter your brain structure.",
               "url": "https://stream.basefm.co.nz:8443/Base256AAC",
               "icon": "http://db.radioline.fr/pictures/radio_1b34ac132310c975f847aed2a948a318/logo200.jpg?size=200",
               "image": "https://www.idlewp.com/wp-content/uploads/2022/01/rapper-wallpaper-idlewp-1.jpg",
               "lang": "English",
               "disliked": false,
               "category": "hip hop",
               "order": 3
           },
           {
               "id": 4,
               "name": "104",
               "tagline": "English Hits",
               "color": "0xff066c53",
               "desc": "",
               "url": "https://zfm0.radioca.st/stream/1/",
               "icon": "https://radiosindia.com/images/foxfm.jpg",
               "image": "https://i1.sndcdn.com/artworks-000281755367-4ngosl-t500x500.jpg",
               "lang": "English",
               "category": "Electronic",
               "disliked": false,
               "order": 4
           },
           {
               "id": 5,
               "name": "95",
               "tagline": "London UK Asian Music",
               "color": "0xff0d487d",
               "desc": "",
               "url": "https://ssl.shoutcaststreaming.us:8014/stream/1/",
               "icon": "https://static.radio.net/images/broadcasts/5d/9c/37907/1/c175.png",
               "image": "https://as2.ftcdn.net/v2/jpg/03/06/93/37/1000_F_306933785_6TuEd8xTcaruBbkHaHaY1PuioDuOcnEZ.jpg",
               "lang": "English",
               "category": "jazz",
               "disliked": false,
               "order": 5
           },
           {
               "id": 6,
               "name": "94",
               "tagline": "Today's Hits",
               "color": "0xff27383e",
               "desc": "",
               "url": "https://stream.camfm.co.uk/camfm",
               "icon": "https://static.radio.net/images/broadcasts/8d/76/3600/1/c175.png",
               "image": "https://guitar.com/wp-content/uploads/2021/06/mayer-sob-rock@1400x1050.jpg",
               "lang": "English",
               "category": "rock",
               "disliked": false,
               "order": 6
           },
           {
               "id": 7,
               "name": "93",
               "tagline": "Love Songs",
               "color": "0xffa06a37",
               "desc": "The brain responds to music the same way it responds to something that you eat.",
               "url": "https://icecast.easystream.co.uk:8000/herefordFM",
               "icon": "https://mytuner.global.ssl.fastly.net/media/tvos_radios/4evkagl48buu.jpeg",
               "image": "https://media.proprofs.com/images/QM/user_images/2503852/New%20Project%20(91)(109).jpg",
               "lang": "Hindi",
               "category": "pop",
               "disliked": false,
               "order": 7
           },
           {
               "id": 8,
               "name": "107",
               "tagline": "Rocking Retro Hits",
               "color": "0xff090909",
               "desc": "Your heartbeat changes to mimics the music you listen to.",
               "url": "https://node-25.zeno.fm/v2zfmxef798uv?rj-ttl=5&rj-tok=AAABgQRS9fUA4eEEgZWxq-PIRA",
               "icon": "https://mytuner.global.ssl.fastly.net/media/tvos_radios/uvclzz6a6d7x.jpeg",
               "image": "https://i.pinimg.com/originals/7f/f6/13/7ff613ed815f1eb56a90794ec64eecfe.jpg",
               "lang": "Hindi",
               "category": "classic",
               "disliked": false,
               "order": 8
           }
   ]
   
